CREATE TABLE discovery_assessments (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  school_name TEXT NOT NULL,
  contact_person TEXT NOT NULL,
  contact_role TEXT,
  intake_grades TEXT,
  apps_per_year TEXT,
  accepted_per_year TEXT,
  intake_period TEXT,
  access_website BOOLEAN DEFAULT FALSE,
  access_google_forms BOOLEAN DEFAULT FALSE,
  access_pdf BOOLEAN DEFAULT FALSE,
  access_email BOOLEAN DEFAULT FALSE,
  access_whatsapp BOOLEAN DEFAULT FALSE,
  access_social BOOLEAN DEFAULT FALSE,
  access_physical BOOLEAN DEFAULT FALSE,
  info_parent BOOLEAN DEFAULT FALSE,
  info_learner BOOLEAN DEFAULT FALSE,
  info_prev_school BOOLEAN DEFAULT FALSE,
  info_academic BOOLEAN DEFAULT FALSE,
  info_medical BOOLEAN DEFAULT FALSE,
  info_boarding BOOLEAN DEFAULT FALSE,
  info_sibling BOOLEAN DEFAULT FALSE,
  issue_missing BOOLEAN DEFAULT FALSE,
  issue_incorrect BOOLEAN DEFAULT FALSE,
  issue_blurry BOOLEAN DEFAULT FALSE,
  issue_duplicate BOOLEAN DEFAULT FALSE,
  issue_incomplete BOOLEAN DEFAULT FALSE,
  issue_contact BOOLEAN DEFAULT FALSE,
  issue_late BOOLEAN DEFAULT FALSE,
  issue_confusion BOOLEAN DEFAULT FALSE,
  store_drive BOOLEAN DEFAULT FALSE,
  store_network BOOLEAN DEFAULT FALSE,
  store_local BOOLEAN DEFAULT FALSE,
  store_email BOOLEAN DEFAULT FALSE,
  store_printed BOOLEAN DEFAULT FALSE,
  improve_admin BOOLEAN DEFAULT FALSE,
  improve_docs BOOLEAN DEFAULT FALSE,
  improve_reminders BOOLEAN DEFAULT FALSE,
  improve_comms BOOLEAN DEFAULT FALSE,
  improve_visibility BOOLEAN DEFAULT FALSE,
  improve_speed BOOLEAN DEFAULT FALSE,
  improve_tracking BOOLEAN DEFAULT FALSE,
  improve_records BOOLEAN DEFAULT FALSE,
  improve_compliance BOOLEAN DEFAULT FALSE,
  tool_gforms BOOLEAN DEFAULT FALSE,
  tool_excel BOOLEAN DEFAULT FALSE,
  tool_gsheets BOOLEAN DEFAULT FALSE,
  tool_outlook BOOLEAN DEFAULT FALSE,
  tool_whatsapp BOOLEAN DEFAULT FALSE,
  tool_sms BOOLEAN DEFAULT FALSE,
  future_reminders BOOLEAN DEFAULT FALSE,
  future_tracking BOOLEAN DEFAULT FALSE,
  future_dashboard BOOLEAN DEFAULT FALSE,
  future_ai BOOLEAN DEFAULT FALSE,
  future_whatsapp BOOLEAN DEFAULT FALSE,
  future_analytics BOOLEAN DEFAULT FALSE,
  future_multiuser BOOLEAN DEFAULT FALSE,
  future_multicampus BOOLEAN DEFAULT FALSE,
  process_description TEXT,
  naming_explain TEXT,
  parent_questions TEXT,
  parent_confusion TEXT,
  statuses TEXT,
  role_initial TEXT,
  role_docs TEXT,
  role_approval TEXT,
  role_comms TEXT,
  time_sinks TEXT,
  infra_limits TEXT,
  final_comments TEXT,
  signoff_name TEXT,
  signoff_date DATE,
  created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE discovery_assessments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "public_insert_assessments" ON discovery_assessments
  FOR INSERT WITH CHECK (true);

CREATE POLICY "service_role_read_assessments" ON discovery_assessments
  FOR SELECT USING (auth.role() = 'service_role' OR auth.role() = 'authenticated');
